apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Set the maximum number of pods that can be unavailable during the update
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: abhinavs2000/flask-app-trial3:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /healthz  # Specify the endpoint for the readiness probe
            port: 5000
          initialDelaySeconds: 5  # Wait for 5 seconds before the first probe
          periodSeconds: 5  # Probe every 5 seconds
        livenessProbe:
          httpGet:
            path: /healthz  # Specify the endpoint for the liveness probe
            port: 5000
          initialDelaySeconds: 10  # Wait for 10 seconds before the first probe
          periodSeconds: 10  # Probe every 10 seconds
